#!/bin/bash

# Script to apply migration to Supabase database using SQL Editor
# This migration adds diocese admin assignment functionality

echo "📋 Migration: Diocese Admin Assignments"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To apply this migration, follow these steps:"
echo ""
echo "1. Open your Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/pdwajdbmhpuigzlnjbqa/editor/sql"
echo ""
echo "2. Click 'New Query'"
echo ""
echo "3. Copy the contents of this file:"
echo "   supabase/migrations/12_add_diocese_admin_assignments.sql"
echo ""
echo "4. Paste it into the SQL Editor"
echo ""
echo "5. Click 'Run' to execute the migration"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Or, if you have PostgreSQL client installed, run:"
echo ""
echo "  # Get your database URL from Supabase Dashboard > Settings > Database"
echo "  # Then run:"
echo "  psql 'your-connection-string' -f supabase/migrations/12_add_diocese_admin_assignments.sql"
echo ""
